repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: debug-statements # Checks for breakpoint() + debuggers
      - id: check-merge-conflict # Checks for merge conflict strings
      - id: check-toml # Checks toml parse-ability
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.7
    hooks:
      - id: ruff
        name: "Ruff checks and fixes"
        args: [--fix]
      - id: ruff-format
        name: "Ruff format"
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        name: "Check type hints"
        types: [python]
        verbose: true
